trigger:
  branches:
    include:
      - 'main'

  paths:
    exclude:
      - '/**/*.md'
      - '/**/*.markdown'
      - '/**/*.erb'

pr:
  branches:
    include:
      - '*'

  paths:
    exclude:
      - '/**/*.md'

jobs:
  - template: ./ci.yml
    parameters:
      unitTest: true
      goVersions:
        - value: '1.23.4'
          ymlSafeName: '1_23_6'

      vmImages:
        - value: 'ubuntu-20.04'
          ymlSafeName: ubuntu_20_04
