trigger:
  branches:
    include:
    - 'master'

  paths:
    exclude:
      - '/**/*.md'
      - '/**/*.markdown'
      - '/**/*.erb'

pr:
  branches:
    include:
    - '*'

  paths:
    exclude:
      - '/**/*.md'

jobs:
- template: ./ci.yml
  parameters:
    goVersions:
    - value: '1.12.10'
      ymlSafeName: '1_12_10'

    vmImages:
    - value: 'ubuntu-16.04'
      ymlSafeName: ubuntu_16_04
