trigger:
  branches:
    include:
      - 'master'

  paths:
    exclude:
      - '/**/*.md'
      - '/**/*.markdown'
      - '/**/*.erb'

pr:
  branches:
    include:
      - '*'

  paths:
    exclude:
      - '/**/*.md'

jobs:
  - template: ./ci.yml
    parameters:
      unitTest: true
      
      goVersions:
        - value: '1.16.2'
          ymlSafeName: '1_16_2'

      vmImages:
        - value: 'ubuntu-20.04'
          ymlSafeName: ubuntu_20_04