# This template will generate a list of jobs that will run. The
# jobs created will correspond to the cross product of the
# vmImages and goVersions specified by the parameters.

parameters:
  goVersions: []
  vmImages: []

jobs:

- job: build
  displayName: 'Build: '
  variables:
    GO_PATH_FOR_CACHE: '/home/vsts/go'

  # Build on each combination of supported OS and Go version
  strategy:
    matrix:
      ${{ each goVersion in parameters.goVersions }}:
        ${{ each vmImage in parameters.vmImages }}:
          OS_${{ vmImage.ymlSafeName }}_GO_${{ goVersion.ymlSafeName }}:
            vmImage: ${{ vmImage.value }}
            goVersion: ${{ goVersion.value }}
  
  pool:
    vmImage: $(vmImage)

  steps:
  - task: GoTool@0
    displayName: 'Install correct version of Go'
    inputs:
      version: $(goVersion)

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      chmod +x ./scripts/*.sh
    displayName: 'Set Scripts as Executable'

  - task: CacheBeta@0
    inputs:
      key: gopathpkgmod | "$(vmImage)" | "$(goVersion)"
      path: $(GO_PATH_FOR_CACHE)/pkg/mod
    displayName: Cache Go Modules
    
  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      ./scripts/lint-check-go.sh
    displayName: 'Run Lint Check'

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      ./scripts/build.sh
    displayName: 'Run Build Script'

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      ./scripts/acctest.sh
    displayName: 'Run Acceptance Tests'
    env:
      AZDO_ORG_SERVICE_URL: $(ACC_TEST_AZDO_ORG_URL)
      AZDO_PERSONAL_ACCESS_TOKEN: $(ACC_TEST_AZDO_PAT)
