run:
  deadline: 10m10s
  modules-download-mode: vendor

issues:
  max-per-linter: 0
  max-same-issues: 0

timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - govet
    - whitespace
    - asciicheck

linters-settings:
  errcheck:
    check-blank: true
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).ForceNew
      - strconv.*
      - fmt.*

  tagalign:
    sort: true