version: 2

env:
  - COSIGN_YES=true

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}"

archives:
  - formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

sboms:
  - id: default
    artifacts: source

checksum:
  extra_files:
    - glob: "terraform-registry-manifest.json"
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - id: gpg
    cmd: gpg
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    artifacts: checksum
  - id: cosign
    signature: "${artifact}.sbom.json.bundle"
    cmd: cosign
    args:
      - sign-blob
      - --new-bundle-format
      - --bundle
      - "${signature}"
      - "${artifact}"
    artifacts: checksum

release:
  github:
    owner: Patrick-Kappen
    name: terraform-provider-azuredevops
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

changelog:
  disable: true
