name: Dependency Check

on:
  pull_request:
    branches: [ "main" ]

jobs:

  depscheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Dependency Check
      run: make depscheck
