name: Go lint

on:
  pull_request:
    branches: [ "main" ]

jobs:

  go-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12


