name: Terrafmt check

on:
  pull_request:
    branches: [ "main" ]

jobs:

  terrafmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Terrafmt Check
      run: |
        go install github.com/katbyte/terrafmt@latest
        make terrafmt-check
